pub mod entity_sysconfig;
pub mod entity_sysuser;
pub mod entity_sysmenu;
pub mod entity_sysnotice;
pub mod entity_sysorg;
pub mod entity_syspos;
pub mod entity_sysrole;
pub mod  entity_sysuser_extorg;
pub mod entity_sysuser_role;